server:
  port: 8071
spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        #native:
          #search-locations: "classpath:/config"
          #search-locations: "file:///Users//prashanthrr//Documents//config"
        git:
          uri: "https://github.com/everlastingspring/Config-server-files.git"
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true
  #rabbitmq:
    #host: "localhost"
    #port: 5672
    #username: "guest"
    #password: "guest"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
encrypt:
  key: "6sJ3pG85dAa7rLWnFb2hDvU09ExC4QwK"

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
