apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: technobank
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2025-01-25T15:21:23Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: accounts
  namespace: default
  resourceVersion: "6707"
  uid: 46e3bb31-0d33-4f43-b1da-8a2827c8a6fc
spec:
  clusterIP: 10.97.195.55
  clusterIPs:
  - 10.97.195.55
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: accounts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
